image: docker:1.12

services:
  - docker:dind

variables:
  # change DOCKER_DRIVER to overlay for increased I/O performance
  DOCKER_DRIVER: overlay
  DOCKER_IMAGE_URL: "reg01.binarapps.com/placek/pair_on_docker"

stages:
  - build

before_script:
  - docker info

build-image:
  stage: build
  only:
    - master
  tags:
    - dind
  variables:
    IMAGE_TAG: "latest"
  script:
    - docker build -t "$DOCKER_IMAGE_URL:$IMAGE_TAG" .
    - docker push "$DOCKER_IMAGE_URL:$IMAGE_TAG"
